spring:
  application:
    name: jianyi-user

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

info:
  server.name: ${spring.application.name}
  server.port: ${server.port}
